name: Deploy Frontend Pages

on:
  # 允许手动触发
  workflow_dispatch: {}

  # 当 frontend/ 目录下的文件被推送到 main 分支时自动触发
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - '.github/workflows/deploy-frontend.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: 'generage-short-link' # 【请替换】您在Cloudflare上创建的Pages项目名称
          directory: 'frontend' # 要部署的目录
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}